Overhaul
Superdao-DAO/Superdao-DAO.github.io pull request #5
Opened 2018-02-08 21:54 UTC by coderwithattitude

recommended fixes.

2018-02-08 23:44 UTC, adibas03 approved these changes

2018-02-08 23:44 UTC, adibas03 commented on index.html
> +                                                <p>We have taken steps to modify our funding rounds to a “Pre-sale” or “Pre-sale” only efforts, cutting down on the time needed to market an “ICO” and
"Pre-Sale" repeated twice

2018-02-09 03:55 UTC, adibas03 requested changes

2018-02-09 03:55 UTC, adibas03 commented on js/myscript.js
> +<<<<<<< HEAD
un-resolved conflict

2018-02-16 14:02 UTC, coderwithattitude commented
@adibas03  kindly give final review

2018-02-16 18:39 UTC, adibas03 approved these changes
Looks good

2018-02-17 16:52 UTC, merged